import './globals.scss';
import 'swiper/css/bundle';
import { Poppins } from 'next/font/google';
import Providers from '@/components/provider';
import { SITE_URL } from '@/config/api';

export const metadata = {
  metadataBase: new URL(SITE_URL),
  title: 'Supplefied - Premium Supplements Store',
  description: 'Generated by create next app',
  icons: {
    icon: '/assets/img/logo/slogo.png',
    shortcut: '/assets/img/logo/slogo.png',
    apple: '/assets/img/logo/slogo.png',
  },
}


const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--tp-ff-poppins",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
